// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timesheet.Agent.Infra.Db;

#nullable disable

namespace Timesheet.Agent.Infra.Db.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    [Migration("20260527195340_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("Timesheet.Agent.Domain.ConfiguracaoLocal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackendBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("JwtAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("JwtRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimaSincronizacaoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracaoLocal", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConfiguracaoLocal_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("Timesheet.Agent.Domain.EstadoJornadaAtual", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtualizadoEm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJornada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoInput")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadoJornadaAtual", null, t =>
                        {
                            t.HasCheckConstraint("CK_EstadoJornadaAtual_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("Timesheet.Agent.Domain.MarcacaoLocal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfirmadoPeloUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriadoEm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJornada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HorarioEfetivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("HorarioRegistrado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProximaTentativaEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sincronizada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("TentativasSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErroSync")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sincronizada", "ProximaTentativaEm")
                        .HasDatabaseName("IX_MarcacaoLocal_Sincronizada_ProximaTentativaEm");

                    b.ToTable("MarcacaoLocal", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarcacaoLocal_Origem", "Origem IN ('AGENTE_AUTOMATICO','AGENTE_CONFIRMADO')");

                            t.HasCheckConstraint("CK_MarcacaoLocal_Tipo", "Tipo IN ('INICIO_JORNADA','SAIDA_ALMOCO','RETORNO_ALMOCO','FIM_JORNADA')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
